Calculate nearest tag if only one range tag is provided
GoodRequest/jira-changelog pull request #4
Opened 2023-09-22 14:43 UTC by lubomir-dlhy

2023-09-25 05:31 UTC, gr-miroslava-filcakova requested changes

2023-09-25 05:31 UTC, gr-miroslava-filcakova commented on src/cli.js
> +			range.from = range.from ? range.from : allTags[rangeToTagIndex - 1]
Tu by som mozno este skontrolovala aky je realne ten index. Lebo ak je to prvy tag ( index 0 ) toto sa ti zrejme zrube.

2023-09-26 07:39 UTC, lubomir-dlhy commented on src/cli.js
> +			range.from = range.from ? range.from : allTags[rangeToTagIndex - 1]
@gr-miroslava-filcakova pridal som validaciu

2023-09-26 09:45 UTC, gr-miroslava-filcakova approved these changes

2023-09-26 09:45 UTC, merged